spring:
  rabbitmq:
    addresses: 112.74.61.201:5672
    username: xd
    password: Xd123456
    virtual-host: /
    connection-timeout: 15000

  http:
    encoding:
      charset: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/rabbit?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      initial-size: 10
      min-idle: 5
      max-active: 50
      max-wait: 60000
server:
  port: 8001


